# Additional Hibernate Properties

api.security.token.secret=${JWT_SECRET:my-secret-key}
spring.datasource.test-on-borrow=true
spring.datasource.validation-query=SELECT 1
aws.accessKeyId=
aws.secretAccessKey=
aws.region=
aws.s3.bucket=

# Spring Datasource Configuration for Homologação
spring.datasource.url=jdbc:mysql://localhost:3306/homologacao_db
spring.datasource.username=root
spring.datasource.password=Narutinho123

# Spring JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Additional Hibernate Properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.open-in-view=true
spring.main.allow-circular-references=true