package com.app.domain.model.Product;

public enum StatusProduct {

    // STATUS DE RECOMMENDEDPRODUCTS
    REQUESTSENT("REQUESTSENT"), //QUANDO CRIA A INDICACAO E ENVIA
    OWNERNOTIFIED("OWNERNOTIFIED"), //DEPOIS DE 20 MINUTOS O DONO E NOTIFICADO
    WAITINGFORAPPROVAL("WAITINGFORAPPROVAL"),//DEPOIS DE 1 DIA SE O DONO VISUALIZAR E NAO RESPONDER A SOLICITACAO
    APPROVED("APPROVED"), //APROVADO
    DENIED("DENIED"), //NEGADO
    AVAILABLE("AVAILABLE"), //DISPONIVEL
    UNAVAILABLE("UNAVAILABLE"), //INDISPONIVEL (PRODUTO ARQUIVADO POR EX OU A OWNER NAO QUER MAIS)
    WAITINGCONFIRMATION("WAITING CONFIRMATION FROM RESERVER"), //RESERVADO MAS PERTO DA DATA DE EXPIRACAO E O USUARIO QUE RESERVOU NAO CONFIRMOU
    RESERVED("RESERVED"); //PRODUTO RESERVADO


    private String status_product;

    private StatusProduct(String status_product) {this.status_product = status_product;}

    public String getStatus_product() {
        return status_product;
    }

}
